[package]
name = "viktor"
version = "0.1.0"
edition = "2021"

[dependencies]
ollama = { path = "./ollama" }
tools = { path = "./tools" }
tokio = "1.45.1"
futures = "0.3.31"
serde = "1.0.219"
serde_json = "1.0.140"
tempfile = "3.20.0"
regex = "1.11.1"
