[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0"
fuzzy-matcher = "0.3"
walkdir = "2.3"
tokio = { version = "1", features = ["fs"] }
ignore = "0.4.23"
ollama = { path = "../ollama" }
serde = "1.0.219"
serde_json = "1.0.140"
